using System.Collections.Generic;

namespace gMKVToolNix.Localization
{
    public partial class JsonLocalizationService
    {
        private static readonly Dictionary<string, string> _englishDefaults = new Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase)
        {
            { "UI.Common.Dialog.AreYouSureTitle", "Are you sure?" },
            { "UI.Common.Dialog.ErrorMessage", "An error has occurred!{0}{0}{1}" },
            { "UI.Common.Dialog.ErrorTitle", "Error!" },
            { "UI.Common.Dialog.ExceptionMessage", "An exception has occurred!{0}{0}{1}" },
            { "UI.Common.Dialog.ExceptionTitle", "An exception has occurred!" },
            { "UI.Common.Dialog.SelectDirectoryPlaceholder", "Select directory" },
            { "UI.Common.Dialog.SuccessTitle", "Success!" },
            { "UI.Common.Errors.ExtractionRunningBeforeClose", "There is an extraction process running! Please abort before closing!" },
            { "UI.Common.False", "False" },
            { "UI.Common.NotSet", "Not Set!" },
            { "UI.Common.Status.Extracting", "Extracting..." },
            { "UI.Common.Status.ExtractionCompleted", "Extraction completed!" },
            { "UI.Common.True", "True" },
            { "UI.ContextMenu.SelectAllAttachmentTracks", "Select All Attachments Tracks" },
            { "UI.ContextMenu.SelectAllAudioTracks", "Select All Audio Tracks" },
            { "UI.ContextMenu.SelectAllChapterTracks", "Select All Chapter Tracks" },
            { "UI.ContextMenu.SelectAllSubtitleTracks", "Select All Subtitle Tracks" },
            { "UI.ContextMenu.SelectAllTracks", "Select All Tracks" },
            { "UI.ContextMenu.SelectAllVideoTracks", "Select All Video Tracks" },
            { "UI.ContextMenu.UnselectAllTracks", "Unselect All tracks" },
            { "UI.Controls.TreeView.Errors.GetStateFailed", "Error getting TreeNode state." },
            { "UI.Controls.TreeView.Errors.NodeNotInTree", "The node does not belong to a tree." },
            { "UI.Controls.TreeView.Errors.SetStateFailed", "Error setting TreeNode state." },
            { "UI.JobManager.Actions.Abort", "Abort" },
            { "UI.JobManager.Actions.AbortAll", "Abort All" },
            { "UI.JobManager.Actions.Group", "Actions" },
            { "UI.JobManager.Actions.LoadJobs", "Load Jobs..." },
            { "UI.JobManager.Actions.Popup", "Popup" },
            { "UI.JobManager.Actions.Remove", "Remove" },
            { "UI.JobManager.Actions.RunJobs", "Run Jobs" },
            { "UI.JobManager.Actions.SaveJobs", "Save Jobs..." },
            { "UI.JobManager.Dialogs.SelectJobFileTitle", "Select job file..." },
            { "UI.JobManager.Dialogs.SelectJobsFileTitle", "Select jobs file..." },
            { "UI.JobManager.Errors.ExceptionForJob", "Exception for job {0}: {1}{2}" },
            { "UI.JobManager.Errors.NoJobsAvailable", "There are no available jobs to run!" },
            { "UI.JobManager.Errors.UnsupportedExtractionMode", "Unsupported Extraction Mode!" },
            { "UI.JobManager.Jobs.ChangeToReadyStatus", "Change to Ready Status" },
            { "UI.JobManager.Jobs.DeselectAll", "Deselect All" },
            { "UI.JobManager.Jobs.Group", "Jobs" },
            { "UI.JobManager.Jobs.SelectAll", "Select All" },
            { "UI.JobManager.Progress.CurrentProgress", "Current Progress" },
            { "UI.JobManager.Progress.CurrentTrack", "Current Track" },
            { "UI.JobManager.Progress.Group", "Progress" },
            { "UI.JobManager.Progress.TotalProgress", "Total Progress" },
            { "UI.JobManager.Success.JobsCompleted", "The jobs completed successfully!" },
            { "UI.JobManager.Success.JobsLoaded", "The jobs were loaded successfully!" },
            { "UI.JobManager.Success.JobsSaved", "The jobs were saved successfully!" },
            { "UI.JobManager.Title", "Job Manager" },
            { "UI.Log.Dialogs.ClearLogQuestion", "Are you sure you want to clear the log?" },
            { "UI.Log.Dialogs.SelectFilenameTitle", "Select filename for the log..." },
            { "UI.Log.Success.LogSaved", "The log was saved to {0}!" },
            { "UI.LogForm.Actions.ClearLog", "Clear Log" },
            { "UI.LogForm.Actions.Close", "Close" },
            { "UI.LogForm.Actions.CopySelection", "Copy Selection" },
            { "UI.LogForm.Actions.Group", "Actions" },
            { "UI.LogForm.Actions.Refresh", "Refresh" },
            { "UI.LogForm.Actions.Save", "Save..." },
            { "UI.LogForm.Log.Group", "Log" },
            { "UI.LogForm.Title", "Log" },
            { "UI.MainForm.Actions.Abort", "Abort" },
            { "UI.MainForm.Actions.AbortAll", "Abort All" },
            { "UI.MainForm.Actions.ChapterType", "Chapter" },
            { "UI.MainForm.Actions.Extract", "Extract" },
            { "UI.MainForm.Actions.ExtractionMode", "Extract:" },
            { "UI.MainForm.Actions.Group", "Actions" },
            { "UI.MainForm.Actions.JobMode", "Job Mode" },
            { "UI.MainForm.Actions.Log", "Log..." },
            { "UI.MainForm.Actions.Popup", "Popup" },
            { "UI.MainForm.Config.Browse", "Browse..." },
            { "UI.MainForm.Config.Group", "MKVToolnix Directory (you can drag and drop the directory)" },
            { "UI.MainForm.Errors.ValidMatroskaFileRequired", "You must provide a valid Matroska file!" },
            { "UI.MainForm.InputFile.Browse", "Browse..." },
            { "UI.MainForm.InputFile.Group", "Input file (you can drag and drop the file)" },
            { "UI.MainForm.InputFileInfo.Group", "Input File Information" },
            { "UI.MainForm.Log.Group", "Log" },
            { "UI.MainForm.OutputDirectory.Browse", "Browse..." },
            { "UI.MainForm.OutputDirectory.Group", "Output Directory" },
            { "UI.MainForm.OutputDirectory.Lock", "Lock" },
            { "UI.MainForm.Status.Status", "status" },
            { "UI.MainForm.Status.Track", "track" },
            { "UI.MainForm.Title", "gMKVExtractGUI" },
            { "UI.MainForm2.Actions.AddJobs", "Add Jobs" },
            { "UI.MainForm2.Actions.Abort", "Abort" },
            { "UI.MainForm2.Actions.AbortAll", "Abort All" },
            { "UI.MainForm2.Actions.ChapterType", "Chapter" },
            { "UI.MainForm2.Actions.Extract", "Extract" },
            { "UI.MainForm2.Actions.ExtractionMode", "Extract" },
            { "UI.MainForm2.Actions.Group", "Actions" },
            { "UI.MainForm2.Actions.Log", "Log..." },
            { "UI.MainForm2.Actions.Popup", "Popup" },
            { "UI.MainForm2.Actions.ShowJobs", "Jobs..." },
            { "UI.MainForm2.Appearance.Dark", "Dark" },
            { "UI.MainForm2.Appearance.Options", "Options..." },
            { "UI.MainForm2.Config.AutoDetect", "Auto Detect" },
            { "UI.MainForm2.Config.Browse", "Browse..." },
            { "UI.MainForm2.Config.Group", "MKVToolnix Directory (you can drag and drop the directory)" },
            { "UI.MainForm2.ContextMenu.AddInputFiles", "Add Input File(s)..." },
            { "UI.MainForm2.ContextMenu.AllTrackGroup", "All {0} ({1}/{2})" },
            { "UI.MainForm2.ContextMenu.CheckAllTracks", "Check All Tracks ({0}/{1})" },
            { "UI.MainForm2.ContextMenu.CheckTrackGroup", "Check {0}... ({1}/{2})" },
            { "UI.MainForm2.ContextMenu.CollapseAll", "Collapse All" },
            { "UI.MainForm2.ContextMenu.ExpandAll", "Expand All" },
            { "UI.MainForm2.ContextMenu.Filter.Channels", "Channels" },
            { "UI.MainForm2.ContextMenu.Filter.Codec", "Codec" },
            { "UI.MainForm2.ContextMenu.Filter.Forced", "Forced" },
            { "UI.MainForm2.ContextMenu.Filter.Language", "Language" },
            { "UI.MainForm2.ContextMenu.Filter.LanguageIetf", "Language IETF" },
            { "UI.MainForm2.ContextMenu.Filter.Resolution", "Resolution" },
            { "UI.MainForm2.ContextMenu.Filter.TrackName", "Track Name" },
            { "UI.MainForm2.ContextMenu.FilterValueCount", "{0}: [{1}] ({2}/{3})" },
            { "UI.MainForm2.ContextMenu.OpenSelectedFile", "Open Selected File..." },
            { "UI.MainForm2.ContextMenu.OpenSelectedFileFolder", "Open Selected File Folder..." },
            { "UI.MainForm2.ContextMenu.RemoveAllInputFiles", "Remove All Input Files ({0})" },
            { "UI.MainForm2.ContextMenu.RemoveSelectedInputFile", "Remove Selected Input File" },
            { "UI.MainForm2.ContextMenu.TrackGroup.Attachment", "Attachment Tracks" },
            { "UI.MainForm2.ContextMenu.TrackGroup.Audio", "Audio Tracks" },
            { "UI.MainForm2.ContextMenu.TrackGroup.Chapter", "Chapter Tracks" },
            { "UI.MainForm2.ContextMenu.TrackGroup.Subtitle", "Subtitle Tracks" },
            { "UI.MainForm2.ContextMenu.TrackGroup.Video", "Video Tracks" },
            { "UI.MainForm2.ContextMenu.TrackGroupByFilter", "{0} by {1} ({2})..." },
            { "UI.MainForm2.ContextMenu.UncheckAllTracks", "Uncheck All Tracks ({0}/{1})" },
            { "UI.MainForm2.ContextMenu.UncheckTrackGroup", "Uncheck {0}... ({1}/{2})" },
            { "UI.MainForm2.Dialogs.ChangeDefaultOutputDirectoryQuestion", "Are you sure you want to change the currently set ({0}) default output directory?" },
            { "UI.MainForm2.Dialogs.ChangeMkvToolnixPathQuestion", "Do you really want to change the MKVToolNix path?" },
            { "UI.MainForm2.Dialogs.IncludeSubDirectoriesQuestion", "Do you want to include files in subdirectories?" },
            { "UI.MainForm2.Dialogs.OutputDirectoryMissingQuestion", "The output directory \"{0}\" does not exist!{1}{1}Do you want to create it?" },
            { "UI.MainForm2.Dialogs.OutputDirectoryMissingTitle", "Output directory does not exist!" },
            { "UI.MainForm2.Dialogs.SelectInputMatroskaFileFilter", "Matroska files (*.mkv;*.mka;*.mks;*.mk3d;*.webm)|*.mkv;*.mka;*.mks;*.mk3d;*.webm|Matroska video files (*.mkv)|*.mkv|Matroska audio files (*.mka)|*.mka|Matroska subtitle files (*.mks)|*.mks|Matroska 3D files (*.mk3d)|*.mk3d|WebM files (*.webm)|*.webm" },
            { "UI.MainForm2.Dialogs.SelectInputMatroskaFileTitle", "Select an input Matroska file..." },
            { "UI.MainForm2.Dialogs.SelectMkvToolnixDirectoryTitle", "Select MKVToolNix directory..." },
            { "UI.MainForm2.Dialogs.SelectOutputDirectoryTitle", "Select output directory..." },
            { "UI.MainForm2.Dialogs.SubDirectoriesFoundTitle", "Subdirectories found!" },
            { "UI.MainForm2.Errors.AutoDetectLinuxNotFound", "Could not find MKVToolNix in /usr/bin, or in the current directory, or in the ini file!" },
            { "UI.MainForm2.Errors.AutoDetectManualPathHint", "{0}{1}Please download and reinstall or provide a manual path!" },
            { "UI.MainForm2.Errors.AutoDetectWindowsNotFound", "Could not find MKVToolNix in registry, or in the current directory, or in the ini file!" },
            { "UI.MainForm2.Errors.ChapterTypeRequired", "You must select a chapter type!" },
            { "UI.MainForm2.Errors.CuesTrackRequired", "You must select a video, audio, or subtitle track to extract cues!" },
            { "UI.MainForm2.Errors.FileDoesNotExist", "The file {0} does not exist!" },
            { "UI.MainForm2.Errors.FileProcessing", "File: {0} Error: {1}" },
            { "UI.MainForm2.Errors.FolderDoesNotContainMkvToolnix", "The folder does not contain MKVToolNix! {0}" },
            { "UI.MainForm2.Errors.InvalidMatroskaInputFile", "The input file {0}{1}{1}is not a valid Matroska file!" },
            { "UI.MainForm2.Errors.MkvmergeNotFoundInPath", "mkvmerge was not found in path {0}!" },
            { "UI.MainForm2.Errors.MkvToolnixFilesMissing", "The MKVToolNix path provided does not contain MKVToolNix files!" },
            { "UI.MainForm2.Errors.MkvToolnixPathRequired", "You must provide an MKVToolNix path!" },
            { "UI.MainForm2.Errors.NoFilenameProvided", "No filename was provided!" },
            { "UI.MainForm2.Errors.NoNewFiles", "No new files to add!" },
            { "UI.MainForm2.Errors.NoValidMatroskaFiles", "No valid Matroska files were provided!" },
            { "UI.MainForm2.Errors.OutputDirectoryMissingCancelled", "The output directory \"{0}\" does not exist!{1}{1}Extraction was cancelled!" },
            { "UI.MainForm2.Errors.OutputDirectoryRequired", "You haven't specified an output directory!" },
            { "UI.MainForm2.Errors.SelectedNodeNoInfo", "Selected node has no info!" },
            { "UI.MainForm2.Errors.SelectedNodeNoParent", "Selected node has no parent node!" },
            { "UI.MainForm2.Errors.SelectedNodeNullTag", "Selected node has a null tag!" },
            { "UI.MainForm2.Errors.TimecodesTrackRequired", "You must select a video, audio, or subtitle track to extract timecodes!" },
            { "UI.MainForm2.Errors.TrackRequired", "You must select a track to extract!" },
            { "UI.MainForm2.Errors.TrackRequiredForMode", "You must select a track from the file in order to extract {0}!" },
            { "UI.MainForm2.FileOptions.AppendOnDragAndDrop", "Append input on drag and drop" },
            { "UI.MainForm2.FileOptions.DisableTooltips", "Disable tooltips" },
            { "UI.MainForm2.FileOptions.OverwriteExistingFiles", "Overwrite existing files" },
            { "UI.MainForm2.FileOptions.Select", "Select..." },
            { "UI.MainForm2.InputFiles.Group", "Input Files (you can drag and drop files or directories)" },
            { "UI.MainForm2.InputFiles.GroupWithCount", "Input Files (you can drag and drop files or directories) ({0} files)" },
            { "UI.MainForm2.OutputDirectory.Browse", "Browse..." },
            { "UI.MainForm2.OutputDirectory.Group", "Output Directory for Selected File (you can drag and drop the directory)" },
            { "UI.MainForm2.OutputDirectory.SetAsDefault", "Set As Default Directory" },
            { "UI.MainForm2.OutputDirectory.UseDefault", "Use Currently Set Default Directory:" },
            { "UI.MainForm2.OutputDirectory.UseDefaultWithValue", "Use Currently Set Default Directory: ({0})" },
            { "UI.MainForm2.OutputDirectory.UseSource", "Use Source" },
            { "UI.MainForm2.SelectedFileInfo.Group", "Selected File Information" },
            { "UI.MainForm2.SelectedFileInfo.GroupWithFile", "Selected File Information ({0})" },
            { "UI.MainForm2.Status.Status", "status" },
            { "UI.MainForm2.Status.TotalStatus", "status" },
            { "UI.MainForm2.Success.ExtractionCompleted", "The extraction was completed successfully!" },
            { "UI.MainForm2.Title", "gMKVExtractGUI" },
            { "UI.MainForm2.Tooltips.AppendOnDragAndDrop", "Check if you want to append files in the input list on drag and drop.\nUncheck if you want to reset the input list every time you drag and drop a new file." },
            { "UI.MainForm2.Tooltips.AutoDetect", "Press to try and auto-detect the MKVToolNix installation." },
            { "UI.MainForm2.Tooltips.InputFiles", "Contains the list of opened files with their tracks.\nYou can check the individual tracks in order to select them for extracting.\n\nNote: There is a context menu (right-click on the list) that contains many options for batch selecting tracks." },
            { "UI.MainForm2.Tooltips.OverwriteExistingFiles", "Check if you want the output files to always overwrite existing files with the same filename.\nUncheck if you want the output files to automatically be renamed with a different filename to avoid overwriting existing files." },
            { "UI.MainForm2.Tooltips.Select", "Press to display the menu that contains many options for batch selecting tracks." },
            { "UI.MainForm2.Tooltips.ShowPopup", "Check if you want to show a popup message when the extraction is finished." },
            { "UI.MainForm2.Tooltips.UseSourceDirectory", "Check if you want the output files to be saved in the same directory as the source files.\nUncheck if you want to manually select an output directory for ALL extracted files." },
            { "UI.OptionsForm.Actions.Cancel", "Cancel" },
            { "UI.OptionsForm.Actions.Group", "Actions" },
            { "UI.OptionsForm.Actions.OK", "OK" },
            { "UI.OptionsForm.Advanced.Culture", "Culture:" },
            { "UI.OptionsForm.Advanced.Group", "Advanced Options" },
            { "UI.OptionsForm.Attachments.Add", "Add..." },
            { "UI.OptionsForm.Attachments.Default", "Default" },
            { "UI.OptionsForm.Attachments.Group", "Attachments" },
            { "UI.OptionsForm.AudioTracks.Add", "Add..." },
            { "UI.OptionsForm.AudioTracks.Default", "Default" },
            { "UI.OptionsForm.AudioTracks.Group", "Audio Tracks" },
            { "UI.OptionsForm.Chapters.Add", "Add..." },
            { "UI.OptionsForm.Chapters.Default", "Default" },
            { "UI.OptionsForm.Chapters.Group", "Chapters" },
            { "UI.OptionsForm.Defaults", "Defaults" },
            { "UI.OptionsForm.FullRawMode", "Use `full raw` extraction" },
            { "UI.OptionsForm.Info.Group", "Information" },
            { "UI.OptionsForm.Info.Text", "Here you can specify the output filename format for each kind of track.\nPressing the \"Add...\" button you will see the list with the available placeholders and select them.\nPressing the \"Default\" button you will reset the output filename format to its default value." },
            { "UI.OptionsForm.Placeholders.AttachmentFilename", "Attachment Filename" },
            { "UI.OptionsForm.Placeholders.AttachmentFileSizeBytes", "Attachment File Size (bytes)" },
            { "UI.OptionsForm.Placeholders.AttachmentId.Group", "Attachment ID..." },
            { "UI.OptionsForm.Placeholders.AttachmentId.NoFormat", "Attachment ID (No format)" },
            { "UI.OptionsForm.Placeholders.AttachmentId.OneDigit", "Attachment ID (1 digit)" },
            { "UI.OptionsForm.Placeholders.AttachmentId.ThreeDigits", "Attachment ID (3 digits)" },
            { "UI.OptionsForm.Placeholders.AttachmentId.TwoDigits", "Attachment ID (2 digits)" },
            { "UI.OptionsForm.Placeholders.AttachmentMimeType", "Attachment MIME Type" },
            { "UI.OptionsForm.Placeholders.AudioChannels", "Audio Channels" },
            { "UI.OptionsForm.Placeholders.AudioSamplingFrequency", "Audio Sampling Frequency" },
            { "UI.OptionsForm.Placeholders.DirectorySeparator", "Directory Separator" },
            { "UI.OptionsForm.Placeholders.InputFilenameWithExtension", "Input Filename (with extension)" },
            { "UI.OptionsForm.Placeholders.InputFilenameWithoutExtension", "Input Filename (without extension)" },
            { "UI.OptionsForm.Placeholders.TrackCodecId", "Track Codec ID" },
            { "UI.OptionsForm.Placeholders.TrackCodecPrivate", "Track Codec Private" },
            { "UI.OptionsForm.Placeholders.TrackDelay", "Track Delay" },
            { "UI.OptionsForm.Placeholders.TrackEffectiveDelay", "Track Effective Delay" },
            { "UI.OptionsForm.Placeholders.TrackForced", "Track Forced" },
            { "UI.OptionsForm.Placeholders.TrackId.Group", "Track ID..." },
            { "UI.OptionsForm.Placeholders.TrackId.NoFormat", "Track ID (No format)" },
            { "UI.OptionsForm.Placeholders.TrackId.OneDigit", "Track ID (1 digit)" },
            { "UI.OptionsForm.Placeholders.TrackId.ThreeDigits", "Track ID (3 digits)" },
            { "UI.OptionsForm.Placeholders.TrackId.TwoDigits", "Track ID (2 digits)" },
            { "UI.OptionsForm.Placeholders.TrackLanguage", "Track Language" },
            { "UI.OptionsForm.Placeholders.TrackLanguageIetf", "Track Language IETF" },
            { "UI.OptionsForm.Placeholders.TrackName", "Track Name" },
            { "UI.OptionsForm.Placeholders.TrackNumber.Group", "Track Number..." },
            { "UI.OptionsForm.Placeholders.TrackNumber.NoFormat", "Track Number (No format)" },
            { "UI.OptionsForm.Placeholders.TrackNumber.OneDigit", "Track Number (1 digit)" },
            { "UI.OptionsForm.Placeholders.TrackNumber.ThreeDigits", "Track Number (3 digits)" },
            { "UI.OptionsForm.Placeholders.TrackNumber.TwoDigits", "Track Number (2 digits)" },
            { "UI.OptionsForm.Placeholders.VideoPixelHeight", "Video Pixel Height" },
            { "UI.OptionsForm.Placeholders.VideoPixelWidth", "Video Pixel Width" },
            { "UI.OptionsForm.RawMode", "Use `raw` extraction" },
            { "UI.OptionsForm.Advanced.Translations", "Translations..." },
            { "UI.OptionsForm.SubtitleTracks.Add", "Add..." },
            { "UI.OptionsForm.SubtitleTracks.Default", "Default" },
            { "UI.OptionsForm.SubtitleTracks.Group", "Subtitle Tracks" },
            { "UI.OptionsForm.Tags.Add", "Add..." },
            { "UI.OptionsForm.Tags.Default", "Default" },
            { "UI.OptionsForm.Tags.Group", "Tags" },
            { "UI.OptionsForm.TextFilesWithoutBom", "Disable BOM to text files (v96.0+)" },
            { "UI.OptionsForm.Title", "Options" },
            { "UI.OptionsForm.VideoTracks.Add", "Add..." },
            { "UI.OptionsForm.VideoTracks.Default", "Default" },
            { "UI.OptionsForm.VideoTracks.Group", "Video Tracks" },
            { "UI.TranslationEditor.Actions.Close", "Close" },
            { "UI.TranslationEditor.Actions.Create", "Create" },
            { "UI.TranslationEditor.Actions.Group", "Actions" },
            { "UI.TranslationEditor.Actions.NewLocale", "New Locale..." },
            { "UI.TranslationEditor.Actions.Save", "Save" },
            { "UI.TranslationEditor.Actions.Sync", "Sync" },
            { "UI.TranslationEditor.Columns.IsTranslated", "Done" },
            { "UI.TranslationEditor.Columns.Key", "Key" },
            { "UI.TranslationEditor.Columns.Notes", "Notes" },
            { "UI.TranslationEditor.Columns.Source", "Source" },
            { "UI.TranslationEditor.Columns.Translation", "Translation" },
            { "UI.TranslationEditor.Dialogs.DiscardChanges", "You have unsaved changes for locale {0}. Discard them?" },
            { "UI.TranslationEditor.Dialogs.NewLocaleTitle", "Create New Locale" },
            { "UI.TranslationEditor.Errors.CannotSyncEnglish", "The English master locale cannot be synced!" },
            { "UI.TranslationEditor.Errors.CultureCodeRequired", "You must enter a locale code!" },
            { "UI.TranslationEditor.Errors.LocaleExists", "The locale {0} already exists!" },
            { "UI.TranslationEditor.Errors.SelectCulture", "You must select a locale first!" },
            { "UI.TranslationEditor.Fields.NewCulture", "New Locale:" },
            { "UI.TranslationEditor.Fields.Search", "Search:" },
            { "UI.TranslationEditor.Fields.ShowOnlyUntranslated", "Show only untranslated" },
            { "UI.TranslationEditor.Fields.Summary", "Translated: {0}/{1}" },
            { "UI.TranslationEditor.Fields.TargetCulture", "Locale:" },
            { "UI.TranslationEditor.Fields.Translator", "Translator:" },
            { "UI.TranslationEditor.Grid.Group", "Translations" },
            { "UI.TranslationEditor.Settings.Group", "Translation Settings" },
            { "UI.TranslationEditor.Status.Clean", "All changes saved" },
            { "UI.TranslationEditor.Status.Dirty", "Unsaved changes" },
            { "UI.TranslationEditor.Status.Loading", "Loading locale..." },
            { "UI.TranslationEditor.Success.LocaleCreated", "The locale {0} was created successfully!" },
            { "UI.TranslationEditor.Success.LocaleSaved", "The locale {0} was saved successfully!" },
            { "UI.TranslationEditor.Success.LocaleSynced", "The locale {0} was synced successfully! Added: {1}, Updated: {2}, Removed: {3}" },
            { "UI.TranslationEditor.Title", "Translation Editor" },
            { "UI.TranslationEditor.Tooltips.NewLocale", "Create a new locale from the English master file." },
            { "UI.TranslationEditor.Tooltips.Sync", "Sync the selected locale with the English master file. New keys are added, changed English source text resets those translations, and removed keys are deleted." },
        };
    }
}
