# GitHub Workflow for building and testing a .NET Framework WinForms application
# This workflow is triggered on pushes and pull requests to the 'main' branch.

name: .NET Framework CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # Use a modern Windows runner. 'windows-latest' will point to the newest stable Windows environment (e.g., windows-2022).
    runs-on: windows-latest

    # Environment variables to easily manage your project names
    env:
      SOLUTION_FILE_PATH: gMKVExtractGUI.sln
      TEST_ASSEMBLY_PATTERN: '*gMKVToolnix.Unit.Tests.dll'
      # Define the expected path for the reference assemblies
      FRAMEWORK_REFERENCE_ASSEMBLIES_PATH: "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0"

    steps:
    # Checks out a copy of your repository on the runner.
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET 4.0 Targeting Pack using the VS Installer.
    - name: Install .NET 4.0 Targeting Pack
      run: |
        $vsInstaller = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe"
        $componentID = "Microsoft.VisualStudio.Component.Framework40.TargetingPack"
        Write-Host "Adding component '$componentID'..."
        $process = Start-Process -FilePath $vsInstaller -ArgumentList "modify --installPath (vswhere -latest -property installationPath) --add $componentID --quiet --norestart" -Wait -PassThru
        if ($process.ExitCode -ne 0) {
          Write-Error "VS Installer failed with exit code $($process.ExitCode)"
          exit $process.ExitCode
        }
        Write-Host ".NET 4.0 Targeting Pack installed successfully."
      shell: powershell

    # NEW: Add a diagnostic step to verify the installation of reference assemblies.
    # This helps debug by showing if the files exist at the expected path.
    - name: Verify Reference Assembly Installation
      run: |
        if (Test-Path "${{ env.FRAMEWORK_REFERENCE_ASSEMBLIES_PATH }}") {
          Write-Host "Reference assemblies found at ${{ env.FRAMEWORK_REFERENCE_ASSEMBLIES_PATH }}. Listing contents:"
          Get-ChildItem -Path "${{ env.FRAMEWORK_REFERENCE_ASSEMBLIES_PATH }}"
        } else {
          Write-Error "Reference assemblies directory NOT FOUND at ${{ env.FRAMEWORK_REFERENCE_ASSEMBLIES_PATH }}"
          # Also check the parent directory in case the path is slightly different
          Get-ChildItem -Path "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework" -ErrorAction SilentlyContinue
          exit 1
        }
      shell: powershell

    # Sets up MSBuild in the environment. This step must run after installing any targeting packs.
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Sets up the NuGet CLI for restoring packages.
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'

    # Restores the NuGet packages for your solution.
    - name: Restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    # Builds the solution.
    # UPDATED: Explicitly override the framework path for MSBuild.
    # This directly tells MSBuild where to find the .NET 4.0 assemblies, bypassing any auto-detection issues.
    - name: Build solution
      run: >
        msbuild ${{ env.SOLUTION_FILE_PATH }} 
        /p:Configuration=Release 
        /p:TargetFrameworkVersion=v4.0 
        /p:FrameworkPathOverride="${{ env.FRAMEWORK_REFERENCE_ASSEMBLIES_PATH }}"

    # Runs the unit tests for your project.
    - name: Run unit tests
      run: |
        $vstestPath = vswhere -latest -requires Microsoft.VisualStudio.PackageGroup.TestTools.Core -find **\vstest.console.exe | Select-Object -First 1
        if (-not $vstestPath) {
          Write-Error "vstest.console.exe not found."
          exit 1
        }
        & $vstestPath (Get-ChildItem -Recurse -Filter ${{ env.TEST_ASSEMBLY_PATTERN }} | Where-Object { $_.Name -notlike "*obj*" } | Select-Object -ExpandProperty FullName) /Logger:trx
      shell: powershell

    # Publishes the test results.
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: TestResults/*.trx
        reporter: dotnet-trx
